# Generated by Django 4.1.7 on 2023-04-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vglists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogamelist',
            name='image_url',
        ),
    ]
